
name: 'rt_analytics'
version: '1.0.0'


profile: 'rt_analytics'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"



models:
  rt_analytics:
    telemetry:
      +schema: analytics


